import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/ui/Navbar/Navbar";
import { Footer } from "antd/es/layout/layout";
import Providers from "@/lib/Providers";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Car Servicing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <Providers>
        <body  className="mt-5 w-[90%] mx-auto">
          <Navbar />
          {children}
          <Footer />
        </body>
      </Providers>
    </html>
  );
}
