import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/ui/Navbar/Navbar";
import Providers from "@/lib/Providers";
import Footer from "@/components/ui/Footer/Footer";
import HomeCarousel from "@/components/ui/carousel/Carousel";
import HomeBanner from "@/components/ui/HomeBanner/HomeBanner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Car Servicing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <Providers>
        <body className="mt-20">
          <Navbar />
          <HomeBanner />
          {children}
          <Footer />
        </body>
      </Providers>
    </html>
  );
}
